apiVersion: v1
kind: Service
metadata:
  name: bimonetary-api
  labels:
    app: bimonetary-api
spec:
  ports:
  - port: 80
    targetPort: 80    
    protocol: TCP
    name: http
  type: ClusterIP
  selector:
    app: bimonetary-api
