apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bimonetary-api-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bimonetary-api
        version: v1
    spec:
      containers:
      - name: bimonetary-api
        image: 52.175.72.125:18082/repository/docker-host/bimonetary-api:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: Hosts__BasePath
          value: /
        - name: Features__Mongo__ConnString
          value: mongodb://mongodb:27017
        - name: RpcClients__ExchangeService
          value: exchange:5000
        # resources:
        #   requests:
        #     cpu: 200m
        #     memory: 64Mi
        #   limits:
        #     cpu: 300m
        #     memory: 128Mi
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
