apiVersion: v1
kind: Service
metadata:
  name: bimonetary-api
  labels:
    app: bimonetary-api
spec:
  ports:
  - port: 32503
    targetPort: 80
    nodePort: 32503
    protocol: TCP
    name: http
  type: LoadBalancer
  selector:
    app: bimonetary-api
