apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: exchange
  labels:
    app: exchange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exchange
  template:
    metadata:
      labels:
        app: exchange
    spec:
      containers:
      - name: exchange
        image: vndg/exchange-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: Hosts__Local__Host
          value: "0.0.0.0"
        - name: Hosts__Local__Port
          value: "5000"
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 128Mi
        readinessProbe:
          initialDelaySeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:5000"]
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 10
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:5000"]
