apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-jenkins-data
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.4
    path: /var/nfs/jenkins

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-jenkins-data-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi